### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by CosmoFruit** [KoltesDigital/lerna-dependency-graph#4]
NODE: 14.15.4
OS: Ubuntu 20.04

try to run`yarn graph`

and get error:
`
yarn run v1.22.10
$ lerna-dependency-graph
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
`

whats wrong?

**Comment by KoltesDigital** [comment]
Can you please run `npx lerna-dependency-graph` and report the result?

**Comment by KoltesDigital** [comment]
I fear I built the package on Windows, and the eol at the end of the shebang is not compatible with bash. I'll do the other way around during the weekend.

**Comment by KoltesDigital** [comment]
In the meantime you could edit the file at *node_modules/lerna-dependency-graph/lib/index.js* following the instructions at https://stackoverflow.com/a/40414061.

**Comment by PatrykMilewski** [comment]
@KoltesDigital `npx lerna-dependency-graph` returns the same error. I believe it's the problem with Windows line endings.

**Comment by KoltesDigital** [comment]
I've updated the package. Can you please give it a try?

Note that I've also updated the dependencies, and in particular lerna to version 4. There are some minor breaking changes, and monorepos on older versions might fail to be loaded.

**Comment by PatrykMilewski** [comment]
> I've updated the package. Can you please give it a try?
> 
> Note that I've also updated the dependencies, and in particular lerna to version 4. There are some minor breaking changes, and monorepos on older versions might fail to be loaded.

Works great now! Tested on the MacOS

**Comment by KoltesDigital** [comment]
Thanks!
