### ISSUE TITLE
Tool doesn't work for Apple ARM M1 CPUs

### ISSUE THREAD

**Issue by PatrykMilewski** [KoltesDigital/lerna-dependency-graph#6]
Hello,

Today I've been trying to use this tool in a new repository, but it simply doesn't work. The command I'm trying to execute is:
```
npx lerna-dependency-graph -o test.jpg -f jpg 
```
and then the output:
```
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn dot ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn dot',
  path: 'dot',
  spawnargs: [ '-Tjpg', '-otest.jpg' ]
}
```
It doesn't work for png, plain, pdf and any other file format, that is passed with `-f` or `--outputFormat` flag.

However it works when command is executed without any flags, for example `npx lerna-dependency-graph` prints dependency tree in text format to the console.

The only thing that comes to my mind, that might be an issue, is that I'm using Apple ARM architecture and some libraries that this tool use under the hood, might not like it, but I can't confirm that. But previously, it was working fine for the same command on Mac with x86 CPU.

**Comment by KoltesDigital** [comment]
Hi,

The library relies on the `dot` command to generate images from text. `dot` is part of [Graphviz](https://graphviz.org/). It seems you don't have this software: `spawn dot ENOENT` means the `dot` command is not found. Can you please try [installing it](https://graphviz.org/download/#mac)?

**Comment by PatrykMilewski** [comment]
Ohh it makes sense now, thanks! It fixed the issue!

Btw. would it be simpler and more user friendly to add https://github.com/glejeune/node-graphviz as dependency instead? Or the package is not well enough maintained and you prefer to use native Graphviz installation?

**Comment by KoltesDigital** [comment]
Great!

[Looking at the code of this package](https://github.com/glejeune/node-graphviz/blob/master/lib/graphviz.js#L52), it relies on Graphviz installed on the system too, so it won't solve the problem. Anyway, I just see this tool as a tiny wrapper on top of `dot`, I could have written it in Bash script, so I prefer to keep graphviz separated from it.

**Comment by KoltesDigital** [comment]
Well maybe I can improve the error message instead :)

**Comment by PatrykMilewski** [comment]
> Well maybe I can improve the error message instead :)

Sounds good! Thanks!
